#!/bin/sh
# Src: https://github.com/ndim/ndim-utils/blob/main/build-helpers/package-version
# Syntax:
#   $0 <path-to-top_srcdir> <version-stamp-file>
#
# <path-to-top_srcdir> may be relative
# <version-stamp-file> is relative to src/build topdir
old_top=$(pwd)
top_srcdir="${1-.}"
test -d "$top_srcdir" || { \
	echo "Could not change to top_srcdir '$1'" >&2; \
	exit 1; \
}
cd "$top_srcdir"
version_stamp="${2-version-stamp}"

git_describe=`git describe --abbrev=7 --dirty --always --tags || echo devel`
# change tags like "foo-conf-1.2" to "1.2"
echo "$git_describe" | ${SED-sed} 's/^\([A-Za-z0-9_-]\{1,\}\)-\([0-9]\)/\2/;s/-/./;s/-g/-/' | ${TR-tr} -d '\012'
cd "$old_top"
